#:import Window kivy.core.window.Window

#:import color static.color

#:import Base app.labs.base.base.Base
#:import Create app.labs.create.create.Create
#:import Update app.labs.update.update.Update

<Labs>
    title: "Labs"
    icon: "Labs"

    MDFloatLayout:
        size_hint: None, None
        size: Window.size

        ScreenManager:
            id: labs

#            Base:
#            Create:
            Update:
